### ISSUE TITLE
Secret/Key Rotation Support

### ISSUE THREAD

**Issue by kgoto1** [ory/fosite#212]
I'm wondering how I would rotate private keys/secrets since the strategy setup allows only 1.  If I change that, then I assume all existing tokens/jwts will not be valid on introspection/validation?  I think this would be a nice enhancement for key rotation to manage multiple, with 1 being the primary going forward but previous ones are remembered until they expire.

**Comment by arekkas** [comment]
That's a good question, please excuse my late reply but the notification was buried deep in my mailbox. There are two use cases:

1. You want to rotate the key to increase security
2. You want to rotate the key because the previous has been compromised

In the first scenario, you want existing tokens to work. In the second, you want existing tokens to be revoked.

So in total it depends on why you're rotating keys and I currently don't have a straight answer as to which case to prefer.

**Comment by aeneasr** [comment]
This is now supported
