### ISSUE TITLE
Clarify session storage requirements

### ISSUE THREAD

**Issue by damz** [ory/fosite#256]
The different storages defined in oauth2 all have a session parameter to their getters:

```
GetAuthorizeCodeSession(ctx context.Context, code string, session fosite.Session) (request fosite.Requester, err error)
GetAccessTokenSession(ctx context.Context, signature string, session fosite.Session) (request fosite.Requester, err error)
[...]
```

Could you clarify what are the requirements around the `session` parameter and the session retrievable via `request.GetSession()`?

In the current implementations:

* the [storage/memory.go](https://github.com/ory/fosite/blob/master/storage/memory.go) example implementation just ignores the `session` parameter completely
* the [oauth2/fosite_store_sql.go](https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go#L180) implementation in ory/hydra calls `json.Unmarshal` into the provided parameter (uh?), and sets the result in `fosite.Request.Session`; by doing that it seems to assume that (1) the `fosite.Session` implementation is always JSON-serializable and (2) that the provided argument needs to be mutated in place

Thanks in advance for any clarifications.

**Comment by arekkas** [comment]
Hey, this is one of the weirder concepts in the library. The issue is that the session is [an interface](https://github.com/ory/fosite/blob/master/session.go#L32). For this reason, we don't know what concrete type is actually being used within the store. By passing a "prototype" to the store, the store can use the underlying type to unmarshal the value into it. The idea behind it was to decouple the storage implementation from the code that uses the library (where you would use your own session type).

Does that clear up things?

**Comment by damz** [comment]
Thanks @arekkas, all clear now. I didn't realize that `fosite.Session` was actually provided by the consumer, not by the library.
