### ISSUE TITLE
Allow prompt=none for Public Clients

### ISSUE THREAD

**Issue by someone1** [ory/fosite#287]
Since v0.18 this was explicitly prohibited. The comments around this give reasons as to why it was changed to always require consent, but the RFC's mention that if a https redirect uri is provided previous to the request for that client id, we may assume the client is validated (or atleast that the response will go to a whitelisted location). The RFC doc referenced not included in the comments goes on to say:

>    Measures such as claimed "https" scheme redirects MAY be accepted by
>    authorization servers as identity proof.  Some operating systems may
>    offer alternative platform-specific identity features that MAY be
>    accepted, as appropriate.

My use case is to use PKCE (further increasing confidence of a valid client) for my SPA but not need to have my users give consent every time they load the application. Using `prompt=none` in a hidden iFrame I can get a new token without interrupting the user experience. The alternative would be to use server-side auth with a client secret but now I need to manage secrets on the server side (which in non-trivial) and build out a server-side component in addition to my SPA.

**Comment by arekkas** [comment]
Nice! Actually, this was resolved as it broke some tests in the OIDC test suite ( https://github.com/openid-certification/oidctest/issues/97 ). They said it should be allowed and thus this should have been resolved in the latest patch(es) - so something along the lines of 0.20.x.

By the way, PKCE allows you to issue refresh tokens so no need for hidden iframes!

**Comment by someone1** [comment]
Doh! Didn't see that bit, thanks for the update!

I don't think there's a good way to use refresh tokens in a public client like a SPA. Unlike a native client, I don't have access to cryptographically secure storage specific to my SPA - not unless the new Credential Management API is suitable to store this with. Open to suggestions on this front if you have them!

**Comment by arekkas** [comment]
No problem.

Yeah that's typically the issue with SPAs. It really depends on the type of your application (e.g. lots of user input / xss attack surface?) but for apps that fall into categories where it's unlikely but possible for XSS attacks to occur, it is quite difficult to properly store those credentials anywhere safe (cookies -> not safe from XSS, localStorage -> not safe from XSS) so I guess relying on httpOnly + secure cookies for refreshing with `prompt=none` is actually a nice workaround (the oauth2 proxy pattern is really complicated IMO).

**Comment by arekkas** [comment]
This has been resolved in the latest patch - meaning that this is now allowed!

**Comment by HIRANO-Satoshi** [comment]
Hi,

I couldn't find httpOnly in this repo. Is silent refresh available with fosite?

**Comment by aeneasr** [comment]
That would be client side, not provider side (fosite). Silent refresh _is_ possible.

**Comment by marcomenoni** [comment]
Are you sure this has been resolved ?
I got the following error message raised in fosite/handler/openid/validator.go
`
"OAuth 2.0 Client is marked public and requires end-user consent, but \"prompt=none\" was requested."
`

**Comment by HIRANO-Satoshi** [comment]
In my app silent refresh is working without prompt=none. Don't worry.

**Comment by HIRANO-Satoshi** [comment]
Hi, @marcomenoni 

Here is a scenario.

Suppose you use Hydra and your client is an web app. Since you cannot have a refresh token in your web app, you need to do silent refresh.

At the startup of your web it  has to try silent refresh as your web app does not know whether it has a Hydra's session cookie or not, because the cookie is a httpOnly cookie and invisible from JavaScript in your web app. Perform an auth request from a hidden Iframe with prompt='consent' and login_hint='silent_refresh'. The login_hint is is just a string you defined.

Your login provider (consent app) called from Hydra rejects the auth request if skip=false and login_hint='silent_refresh'. Skip=false means your web app does not provide a valid session cookie and does not have a session yet.

When your web app detects the failure of the silent refresh, it opens a visible new iframe, a dialog frame for example, then load Hydra's login URL in the iframe with login_hint=''. 

Your login provider receives an auth request with skip=false and login_hint=''. If your user types a correct password and "remember me", your login provider sends accept with remember=true and remember_for=time to Hydra. Hydra puts a session cookie to your web app with an expiration period you defined with the remember_for parameter.

After the login process your web app has an access token and a session cookie. Before the expiration of the access token, do silent refresh. If the session cookie is valid, your login provider receives skip=true from Hydra. Just return accept to Hydra.

Thanks @someone1 for your advise.
