### ISSUE TITLE
Redis storage

### ISSUE THREAD

**Issue by rps-repo** [ory/fosite#351]
Please use issues only to file potential bugs or request features. For everything else please go to
the [ORY Community](https://community.ory.sh/) or join the [ORY Chat](https://www.ory.sh/chat).

Sorry but forum doesn't work and no one responds on discord.  Can someone give an example of how to use redis for storage?  I see the reference to https://github.com/ory/fosite/blob/master/storage/memory.go but I have no idea how to make redis work with that.

**Comment by aeneasr** [comment]
What issues do you have with the forum? There is no redis example, you can check out the SQL implementation though: https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go

Also redis is kind of the wrong database for this IMO.

**Comment by deepthi-bhattachar** [comment]
Hi... I am new to Golang and trying to get a project code up and running(2 years old code). The code uses OAuthStore for compose.Compose as shown below. 

I am trying to use FositeSQLStore instead of MemoryStore(storage.NewExampleStore()), so far no luck. Any help would be great. Please provide any sample code which implements FositeSQLStore.

//main.go
var authProvider = compose.Compose(
   config,
   oauthStore,
   strategy,
   createUserPasswordGrantHandler,
   createRefreshTokenGrantHandler,
)

//oauth2.go
type OAuthStore struct {
	DB            *sql.DB
	Auth          Authenticator
	TokenDuration time.Duration
	Clock         utils.ClockInterface
}

Thanks in advance.
