### ISSUE TITLE
Independent and scalable authentication and authorization services

### ISSUE THREAD

**Issue by wregis** [ory/fosite#451]
**Is your feature request related to a problem? Please describe.**
I am building a service to use with AWS API Gateway and not everything is clear to me. I plan on using an ECS container to serve authentication and a Lambda to autorize requests. My current provider config is as follows:

	provider = compose.Compose(
		config,
		storage,
		compose.NewOAuth2JWTStrategyWithIssuer(
			privateKey,
			compose.NewOAuth2HMACStrategy(config, secret, nil),
			"MyIssuer",
		),

		nil,

		compose.OAuth2ClientCredentialsGrantFactory,
		compose.OAuth2RefreshTokenGrantFactory,
		compose.OAuth2ResourceOwnerPasswordCredentialsFactory,

		compose.OAuth2TokenIntrospectionFactory,
	)

The dificulties I'm facing:
* If `privateKey` is random (`rsa.GenerateKey(rand.Reader, 2048)`), how can I scale or have the lambda authorize requests? When I restart my local server and make a request I get an `ErrTokenSignatureMismatch` error.
* How can I tell my service what client and/or user is requesting (and was authorized)? I tried to set `session.JWTClaims.Extra["client"] = ar.GetClient().GetID()` and `session.JWTClaims.Subject = ar.GetRequestForm().Get("username")` on the token service, not sure it is the way.
* Should I replace `compose.OAuth2TokenIntrospectionFactory` with `compose.OAuth2StatelessJWTIntrospectionFactory` for this setup? I created a custom storage so that I can validate clients and users on a MySQL database and store tokens on Redis.

I already know it is not the recommended way to use the resource owner password grant but I have to keep this for now.

**Comment by mitar** [comment]
No, private key should not be random. Only in this example it is random. You should provide the same static key in a secure manner to every instance of your server.

In my use of this library, I have logic in the token endpoint which sets `subject` of the token to the client ID, when client credentials grant type is used, otherwise user's ID is set to `subject`. In this way all tokens always have `subject` equal to for whom the access token is in effect.

No, I do not think you have to replace the introspection factory. The stateless anyway does not currently work (see another issue).

**Comment by leeatchison** [comment]
Miter is correct. You want to generate the private key randomly once, then provide the same key to all instances. Make sure to provide it using a secure method.

**Comment by wregis** [comment]
Thanks @mitar , that worked for me. I've created a file with the result of `rsa.GenerateKey(rand.Reader, 2048)` and `x509.MarshalPKCS1PrivateKey` and now load it with `x509.ParsePKCS1PrivateKey` and that works just fine.

i also updated the subject to contain the "client id" or "username@client id", I think this will work (not testes the flow with refresh token, though).
