### ISSUE TITLE
Need to increase the scope(`openid`) inspection in openid `CanHandleTokenEndpointRequest`

### ISSUE THREAD

**Issue by zhangheng-w** [ory/fosite#702]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/fosite/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/fosite/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When OAuth2 and OIDC are used together, OAuth2 requests (Scope! = 'openid), perform the `PopulateTokenEndpointResponse` (flow_explicit_token.go) function should do nothing, but it is not so.  
I think the `CanHandleTokenEndpointRequest` function should be changed to
```go
func (c *OpenIDConnectExplicitHandler) CanHandleTokenEndpointRequest(requester fosite.AccessRequester) bool {
	return requester.GetGrantTypes().ExactOne("authorization_code") && requester.GetGrantedScopes().Has("openid")
}
```

 

### Reproducing the bug

The explicit token flow should check that GrantTypes includes `authorization_code` and Scopes includes `openid`

### Version

v0.42.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

**Comment by james-d-elliott** [comment]
The code you reference is called here: https://github.com/ory/fosite/blob/master/handler/openid/flow_explicit_token.go#L39-L41

There is a check here however for this specific case: https://github.com/ory/fosite/blob/master/handler/openid/flow_explicit_token.go#L50-L52

Is there something I'm missing in regards to why this isn't ideal? Maybe because of this? https://github.com/ory/fosite/blob/master/access_request_handler.go#L95-L117
